<?php
/**
 * Customizer settings: Global Settings > Customizer CSS
 *
 * @package Suki
 **/

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) exit;

$section = 'suki_section_customizer_css';

/**
 * ====================================================
 * Customizer CSS
 * ====================================================
 */

// Use static CSS file
$id = 'customizer_css_static_file';
$wp_customize->add_setting( $id, array(
	'default'     => suki_array_value( $defaults, $id ),
	'sanitize_callback' => array( 'Suki_Customizer_Sanitization', 'toggle' ),
) );
$wp_customize->add_control( new Suki_Customize_Control_Toggle( $wp_customize, $id, array(
	'section'     => $section,
	'label'       => esc_html__( 'Use static CSS file', 'suki' ),
	'description' => wp_kses_post( '<br>' . __( 'If enabled, Customizer CSS would be served via static CSS file that is generated by theme and saved on <code>wp-content/uploads</code> folder (recommended for caching).', 'suki' ) . '<br><br>' . __( 'If disabled, Customizer CSS would be served via inline CSS on the <code>&lt;head&gt;</code> tag of the page.', 'suki' ) ),
	'priority'    => 10,
) ) );